export type MarketplaceListing = {
  _id: string;
  farmerId?: string;
  title?: string;
  assetCategory: string;
  categoryId?: string;
  subCategoryId?: string;
  description: string;
  pricePerDay: number;
  quantity: string;
  minimumRentalDays?: number;
  condition?: "Like New" | "Excellent" | "Good" | "Fair";
  location: string;
  imageUrl?: string;
  farmerName?: string;
  farmerImage?: string;
  ownerId?: string;
  ownerName?: string;
  ownerImage?: string;
  ownerEmail?: string;
  ownerTrustScore?: number;
  ownerFollowerCount?: number;
  ownerLifetimeCompletedOrders?: number;
  oraclePrice?: number;
  oracleConfidence?: number;
  qualityScore?: string;
  stockQuantity?: number;
  availableStock?: number;
  activeOrdersCount?: number;
  nearestEndDate?: number | null;
  purchaseYear?: number;
  assetAge?: number | null;
  totalRentals?: number;
  lifetimeRentals?: number;
  averageRating?: number;
};
